[dependencies]
base = "0.13.2"
itertools = "0.2.2"

[package]
name = "dao-proposal-engine"
version = "0.1.3"
description = "A library for creating, voting on and executing proposals"
repository = "https://github.com/edjcase/motoko_proposal_engine"
keywords = [ "dao", "proposal", "proposals", "vote", "voting" ]
license = "MIT"

[dev-dependencies]
test = "2.0.0"