
[package]
name = "dao-proposal-engine"
version = "2.0.0"
description = "A library for creating, voting on and executing proposals"
repository = "https://github.com/edjcase/motoko_proposal_engine"
keywords = ["dao", "proposal", "proposals", "vote", "voting"]
license = "MIT"

[dependencies]
core = "0.6.0"
stableheapbtreemap = "1.5.0"

[dev-dependencies]
test = "2.0.0"
